### ISSUE TITLE
app_keys.json not found

### ISSUE THREAD

**Issue by nabladev** [jonahar/google-reminders-cli#4]
Hi! I've run against an issue, basically I added the remind.py to my environment in order to be able to run the command eveywhere, the code on my .zshrc file is:
`remind () {
    python3 ~/Documents/google-reminders-cli/remind.py -c "$1" "$2"
}`

But it spits out this error:
`Traceback (most recent call last):
  File "/home/<username>/Documents/google-reminders-cli/remind.py", line 135, in <module>
    main()
  File "/home/<username>/Documents/google-reminders-cli/remind.py", line 131, in main
    invoke_operation(args)
  File "/home/<username>/Documents/google-reminders-cli/remind.py", line 52, in invoke_operation
    client = RemindersClient()
  File "/home/<username>/Documents/google-reminders-cli/reminders_client.py", line 23, in __init__
    self.auth_http = client_utils.authenticate()
  File "/home/<username>/Documents/google-reminders-cli/reminders_client_utils.py", line 27, in authenticate
    with open(APP_KEYS_FILE) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'app_keys.json'
`

I was able to resolve the issue by adding this line to `remind.py` inside the method `authenticate():`
`# Get the direcory where the file is stored`
`appdir = os.path.dirname(os.path.realpath(__file__)) + '/'`

Now it runs smoothly, I was wondering if you are interested in a pull request to integrate di little tweak. Thank you for your work btw, it's an amazing script!

**Comment by jonahar** [comment]
Yes, the keys file needs to be in the current directory. A pull request would be nice. You can just change the assignment line `APP_KEYS_FILE = ...`
Please use something like `os.path.join(os.path.dirname(os.path.realpath(__file__)), 'app_keys.json')` instead of `+ '/'`
